processed 1 task

task 0 'publish'. lines 5-18:
Error: Transaction Effects Status: Iota Move Bytecode Verification Error. Please run the Iota Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: IotaMoveVerificationError, source: Some("_::m::init at offset 1. Cannot call a module's 'init' function from another Move function"), command: Some(0) } }
