processed 19 tasks

init:
A: object(0,0)

task 1 'publish'. lines 9-112:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 12646400,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 114-114:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 116-120:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 4 'run'. lines 122-122:
mutated: object(0,0)
deleted: object(3,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 2272400, non_refundable_storage_fee: 0

task 5 'run'. lines 124-124:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 6 'run'. lines 126-126:
created: object(6,0), object(6,1)
mutated: object(0,0), object(5,0)
gas summary: computation_cost: 1000000, storage_cost: 6011600,  storage_rebate: 2272400, non_refundable_storage_fee: 0

task 7 'run'. lines 128-132:
Error: Error checking transaction input objects: InvalidChildObjectArgument { child_id: object(6,0), parent_id: object(6,1) }

task 8 'run'. lines 134-134:
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2325600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 9 'run'. lines 136-139:
Error: Transaction Effects Status: Invalid command argument at 0. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: TypeMismatch }, source: None, command: Some(1) } }

task 10 'run'. lines 141-141:
created: object(10,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2325600,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 11 'run'. lines 143-143:
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 12 'run'. lines 145-148:
Error: Transaction Effects Status: Invalid command argument at 1. The type of the value does not match the expected type
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 1, kind: TypeMismatch }, source: None, command: Some(0) } }

task 13 'run'. lines 150-150:
created: object(13,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 14 'run'. lines 152-155:
Error: Transaction Effects Status: Invalid command argument at 0. Immutable objects cannot be passed by-value.
Debug of error: CommandArgumentError { arg_idx: 0, kind: InvalidObjectByValue } at command Some(0)

task 15 'run'. lines 157-157:
created: object(15,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 16 'run'. lines 159-162:
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidValueUsage }, source: None, command: Some(1) } }

task 17 'run'. lines 164-164:
created: object(17,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 988000, non_refundable_storage_fee: 0

task 18 'run'. lines 166-166:
Error: Transaction Effects Status: Invalid command argument at 0. Invalid usage of value. Mutably borrowed values require unique usage. Immutably borrowed values cannot be taken or borrowed mutably. Taken values cannot be used again.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: CommandArgumentError { arg_idx: 0, kind: InvalidValueUsage }, source: None, command: Some(1) } }
